### ISSUE TITLE
Huge White Window In The Middle Of The Page

### ISSUE THREAD

**Issue by Davy49** [bewisse/newtab#1] opened 2020-04-22 10:14 UTC
Hi,
I'm currently evaluating your newtab extension on the new chromium version of the edge browser. One thing I don't really care for at all is the huge white page that sits in the center of the newtab page, also at least for me there's a wide black bar at the bottom of the page as well. If I could determine how to get rid of both of these item's I would truly enjoy your extension much much more. Also unless I'm missing/not seeing it, I don't find any setting's option available anywhere on the newtab page whatsoever. To me at least that seems rather strange, all of the other chromium based new tab extension's I've tried have at least offered a setting's option that's available to the user of the extension, this is the very first one that appears not to.
David

**Comment by hao1300** [comment] 2020-04-23 15:05
Thanks for reporting. I have committed a fix and request for the new version to be published. It will generally take a few days for it to go live.

**Comment by Davy49** [comment] 2020-04-26 08:11
Hi hao1300,
I'm impressed that you replied back to me, that tells me that you are genuine in actually caring about what user's of your extension say. I'm really surprised someone else hasn't mentioned this issue before now. If indeed you can somehow prevent that white block from showing all of the time and instead only when needed that will make this extension much much better..at least for me. Since I'm more of a simplistic kind of person, I don't like huge item's on my screen that I can't have some control over, they tend to distract me and effect my focus. Thanks SO much for your response, if that indeed can get corrected, I'll surely try out your extension once again.
David

**Comment by hao1300** [comment] 2020-04-28 13:27
Hi @Davy49, my new version of Smart New Tab is published. It should make it possible to collapse individual sections on the new tab screen. If you can still reproduce the issue, would you mind taking a screenshot a sharing it with me? It definitely sounds like a bug, but for some reasons I can't reproduce the white box in any of my devices.

**Closed** 2020-08-12 13:19 UTC
